In [2]:
from pathlib import Path
import numpy as np
from typing import Literal, Optional
import os
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde
import matplotlib.pyplot as plt
import seaborn as sns


project_root = Path(".").resolve().parent.parent.parent
assert project_root.name == "pep-compass"

In [3]:
import pandas as pd

parents_negative = pd.read_csv(
    project_root
    / "results/data/hydramp/dbaasp/all/dbaasp_clean_leq25.csv"
)
mutants_negative = pd.read_csv(
    project_root
    / "results/mutants/mutants/hydramp/dbaasp/all/dbaasp_clean_parentleq25_direction_threshold=1e-06_token_threshold=0.1_jacobian_mode=approx_jacobian_eps=0.05_leq25.csv"
)

parents_positive = pd.read_csv(
    project_root
    / "results/data/hydramp/dbaasp/all/high_ecoli_activity_leq25.csv"
)
mutants_positive = pd.read_csv(
    project_root
    / "results/mutants/mutants/hydramp/dbaasp/all/high_ecoli_activity_parentleq25_direction_threshold=1e-06_token_threshold=0.1_jacobian_mode=approx_jacobian_eps=0.05_leq25.csv"
    )

In [4]:
def compute_diff(
    parents_df: pd.DataFrame,
    mutants_df: pd.DataFrame,
    match_col_parents: str,
    match_col_mutants: str,
    value_cols: list[str],
    value_preprocessing: Optional[Literal["log"]],
    add_relative: bool,
) -> pd.DataFrame:
    """
    Compute the difference between the mutants and parents for each value column.
    """
    merged = mutants_df.merge(
        parents_df,
        left_on=match_col_mutants,
        right_on=match_col_parents,
        suffixes=("_mutants", "_parents"),
    )
    if value_preprocessing is None:
        vprep_fn = lambda x: x
    elif value_preprocessing == "log":
        vprep_fn = np.log2
    else:
        raise ValueError(f"Invalid value_preprocessing: {value_preprocessing}")
    if value_preprocessing is None:
        value_preprocessing = ""
    else:
        value_preprocessing = "_" + value_preprocessing

    for value_col in value_cols:
        merged[f"{value_col}{value_preprocessing}_diff"] = vprep_fn(
            merged[f"{value_col}_mutants"]
        ) - vprep_fn(merged[f"{value_col}_parents"])
        if add_relative:
            merged[f"{value_col}{value_preprocessing}_diff_relative"] = merged[
                f"{value_col}{value_preprocessing}_diff"
            ] / vprep_fn(merged[f"{value_col}_parents"])
    return merged

In [5]:
mic_bac_columns = parents_negative.head().columns.tolist()[3:]

In [6]:
diff_negative = compute_diff(
    parents_df=parents_negative,
    mutants_df=mutants_negative,
    match_col_parents="description",
    match_col_mutants="parent_id",
    value_cols=mic_bac_columns,
    value_preprocessing="log",
    add_relative=True,
)
diff_positive = compute_diff(
    parents_df=parents_positive,
    mutants_df=mutants_positive,
    match_col_parents="description",
    match_col_mutants="parent_id",
    value_cols=mic_bac_columns,
    value_preprocessing="log",
    add_relative=True,
)

ALL_AA = list("ACDEFGHIKLMNPQRSTVWY")

diff_clean_positive = diff_positive.dropna(subset=["parent", "mutant", "position"]).drop_duplicates(subset=["parent", "mutant", "position"])


mask = (
    (diff_clean_positive["position"] < diff_clean_positive["parent"].str.len()) &
    (diff_clean_positive["position"] < diff_clean_positive["mutant"].str.len())
)
diff_clean_positive = diff_clean_positive[mask]


diff_clean_negative = diff_negative.dropna(subset=["parent", "mutant", "position"]).drop_duplicates(subset=["parent", "mutant", "position"])


mask = (
    (diff_clean_negative["position"] < diff_clean_negative["parent"].str.len()) &
    (diff_clean_negative["position"] < diff_clean_negative["mutant"].str.len())
)
diff_clean_negative = diff_clean_negative[mask]

In [7]:
#merge diffs into one but leave label 0 negative 1 postive
diff_clean_negative['label'] = 0
diff_clean_positive['label'] = 1
diff_clean = pd.concat([diff_clean_negative, diff_clean_positive], ignore_index=True)

In [8]:
diff_clean

,mutant,position,parent,parent_id,A. baumannii ATCC 19606_mutants,E. coli ATCC 11775_mutants,E. coli AIG221_mutants,E. coli AIG222_mutants,K. pneumoniae ATCC 13883_mutants,P. aeruginosa PA01_mutants,...,E. coli Nissle_log_diff_relative,Salmonella enterica ATCC 9150 (BEIRES NR-515)_log_diff,Salmonella enterica ATCC 9150 (BEIRES NR-515)_log_diff_relative,Salmonella enterica (BEIRES NR-170)_log_diff,Salmonella enterica (BEIRES NR-170)_log_diff_relative,Salmonella enterica ATCC 9150 (BEIRES NR-174)_log_diff,Salmonella enterica ATCC 9150 (BEIRES NR-174)_log_diff_relative,L. monocytogenes ATCC 19111 (BEIRES NR-106)_log_diff,L. monocytogenes ATCC 19111 (BEIRES NR-106)_log_diff_relative,label
0,FLGLLFHGVHHVGKWIHGNIHGHH,18,FLGLLFHGVHHVGKWIHGLIHGHH,DBAASP_1001,83.673540,113.194336,105.330060,76.993530,59.806360,55.607685,...,-0.008496,0.383081,0.082083,0.178596,0.018772,0.184985,0.023641,0.330948,0.064074,0
1,FLGLLFHGVHHVGKWIHGIIHGHH,18,FLGLLFHGVHHVGKWIHGLIHGHH,DBAASP_1001,76.766450,109.609700,101.310745,74.697845,50.966095,46.862800,...,-0.018160,0.040210,0.008616,-0.007879,-0.000828,-0.066927,-0.008553,0.051298,0.009932,0
2,FLGLLFHGVHHVGKWIHGEIHGHH,18,FLGLLFHGVHHVGKWIHGLIHGHH,DBAASP_1001,104.181110,125.732240,118.488990,98.296370,80.257400,75.969790,...,0.069494,0.834084,0.178719,0.424473,0.044616,0.654384,0.083631,0.735229,0.142345,0
3,FLGLLFHGVHHVGKWIHGKIHGHH,18,FLGLLFHGVHHVGKWIHGLIHGHH,DBAASP_1001,66.921820,93.771110,87.084960,72.269580,37.082706,35.130596,...,-0.066390,-0.432021,-0.092569,-0.022259,-0.002340,-0.150654,-0.019254,-0.370305,-0.071693,0
4,FLGLLFHGVHHVGKWIHGLIVGHH,20,FLGLLFHGVHHVGKWIHGLIHGHH,DBAASP_1001,77.838580,113.621750,104.875145,75.585450,56.882526,51.541615,...,0.008679,0.231504,0.049604,0.079699,0.008377,0.143732,0.018369,0.206367,0.039954,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106636,LLPWKWIWWKWRR,6,LLPWKWPWWKWRR,DBAASP_10694,42.117832,99.160650,91.479034,61.479840,40.959923,17.017202,...,0.000289,-0.699782,-0.132337,-0.175068,-0.019900,-0.300381,-0.034629,-0.618300,-0.106492,1
106637,LLPWKWKWWKWRR,6,LLPWKWPWWKWRR,DBAASP_10694,56.130257,74.791730,76.946630,90.852234,49.359818,25.131464,...,0.006494,-0.403659,-0.076336,0.027925,0.003174,0.059736,0.006887,-0.313172,-0.053939,1
106638,LLPWKWQWWKWRR,6,LLPWKWPWWKWRR,DBAASP_10694,77.834730,99.605640,95.159950,99.039810,64.883950,38.661720,...,0.076445,0.161648,0.030569,0.361439,0.041085,0.023906,0.002756,-0.014833,-0.002555,1
106639,LLPWKWFWWKWRR,6,LLPWKWPWWKWRR,DBAASP_10694,50.260666,106.336750,93.892250,76.810200,46.730070,20.388280,...,0.012148,-0.505391,-0.095575,-0.127701,-0.014516,-0.206585,-0.023816,-0.469383,-0.080843,1
106640,LLPWKKPWWKWRR,5,LLPWKWPWWKWRR,DBAASP_10694,84.122770,83.858170,85.861275,117.207470,62.171753,38.889763,...,-0.008305,-0.051721,-0.009781,-0.060519,-0.006879,0.055577,0.006407,0.056267,0.009691,1

In [9]:
diff_clean['transition'] = diff_clean.apply(
    lambda row: row['mutant'][int(row['position'])] + row['parent'][int(row['position'])],
    axis=1
)

In [10]:
y = diff_clean['E. coli ATCC 11775_log_diff']

In [11]:
transition_dummies = pd.get_dummies(diff_clean['transition'], prefix='trans', drop_first=True)

In [12]:
transition_dummies

,trans_AD,trans_AE,trans_AF,trans_AG,trans_AH,trans_AI,trans_AK,trans_AL,trans_AM,trans_AN,...,trans_YK,trans_YL,trans_YM,trans_YN,trans_YP,trans_YQ,trans_YR,trans_YT,trans_YV,trans_YW
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106636,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
106637,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
106638,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
106639,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
106640,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# transition_dummies = transition_dummies.mul(diff_clean['label'], axis=0)

In [14]:
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
import statsmodels.api as sm

# X and y
X = transition_dummies.astype(float).values  # no transpose
y = diff_clean['E. coli ATCC 11775_log_diff'].values

# Fit OLS model
X_sm = sm.add_constant(X)  # Adds intercept
ols_model = sm.OLS(y, X_sm)
results = ols_model.fit()

# Extract coefficients & p-values (excluding constant)
coef = results.params[1:]      # pomiń constant
pvals = results.pvalues[1:]    # pomiń constant

model_coef_df = pd.DataFrame({
    "aa_change": transition_dummies.columns,
    "coefficient": coef,
    "p_value": pvals
})

# Display
print(model_coef_df.head())

  aa_change  coefficient   p_value
0  trans_AD    -0.138556  0.067014
1  trans_AE    -0.079255  0.339676
2  trans_AF     0.113565  0.145882
3  trans_AG     0.062853  0.401358
4  trans_AH     0.077217  0.426450

In [15]:
from statsmodels.stats.multitest import multipletests

In [16]:
# --- Apply Benjamini–Hochberg correction (FDR)
reject, pvals_corrected, _, _ = multipletests(model_coef_df["p_value"], method="fdr_bh")

# Add to DataFrame
model_coef_df["p_adj"] = pvals_corrected
model_coef_df["significant_FDR_5%"] = reject

# --- Sort by adjusted p-value for clarity
model_coef_df = model_coef_df.sort_values("p_adj")

In [17]:
model_coef_df[model_coef_df["significant_FDR_5%"]!=True]

    aa_change  coefficient   p_value     p_adj  significant_FDR_5%
39   trans_DE     0.183856  0.014992  0.052471               False
290  trans_SM     0.272294  0.015819  0.054341               False
351  trans_WT    -0.254928  0.015729  0.054341               False
117  trans_HF     0.180833  0.016224  0.055222               False
71   trans_ET     0.182866  0.016803  0.055664               False
..        ...          ...       ...       ...                 ...
160  trans_KM    -0.006897  0.963146  0.973644               False
368  trans_YT     0.006788  0.969066  0.976966               False
85   trans_FN     0.000751  0.992451  0.996687               False
203  trans_MT     0.000939  0.994001  0.996687               False
109  trans_GT     0.000051  0.999522  0.999522               False

[266 rows x 5 columns]

In [18]:
# Wyświetl tylko kolumny, które Cię interesują



print(model_coef_df[["aa_change", "p_value", "p_adj", "significant_FDR_5%"]].head(100))

    aa_change       p_value         p_adj  significant_FDR_5%
50   trans_DR  3.508239e-25  1.301557e-22                True
25   trans_CK  3.158937e-18  5.859828e-16                True
44   trans_DK  1.385494e-17  1.713394e-15                True
64   trans_EL  4.134395e-16  3.834652e-14                True
43   trans_DI  2.030947e-14  1.255802e-12                True
..        ...           ...           ...                 ...
211  trans_NF  9.260378e-03  3.578750e-02                True
360  trans_YI  9.557333e-03  3.655434e-02                True
282  trans_SD  9.773934e-03  3.689639e-02                True
235  trans_PN  9.845667e-03  3.689639e-02                True
237  trans_PR  1.029165e-02  3.818204e-02                True

[100 rows x 4 columns]

In [19]:
significant = model_coef_df.loc[model_coef_df["p_adj"] < 0.1, 
                                ["aa_change", "coefficient", "p_value", "p_adj", "significant_FDR_5%"]]
print(significant.sort_values("p_adj"))

    aa_change  coefficient       p_value         p_adj  significant_FDR_5%
50   trans_DR     0.815313  3.508239e-25  1.301557e-22                True
25   trans_CK     0.696167  3.158937e-18  5.859828e-16                True
44   trans_DK     0.659426  1.385494e-17  1.713394e-15                True
64   trans_EL     0.609080  4.134395e-16  3.834652e-14                True
43   trans_DI     0.682415  2.030947e-14  1.255802e-12                True
..        ...          ...           ...           ...                 ...
299  trans_TA     0.168459  3.307733e-02  9.367702e-02               False
248  trans_QG     0.189081  3.283188e-02  9.367702e-02               False
276  trans_RT    -0.318186  3.304468e-02  9.367702e-02               False
103  trans_GM     0.162839  3.362398e-02  9.450376e-02               False
30   trans_CQ     0.264665  3.407860e-02  9.506135e-02               False

[133 rows x 5 columns]

In [22]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.400
Model:                            OLS   Adj. R-squared:                  0.398
Method:                 Least Squares   F-statistic:                     191.2
Date:                Sun, 09 Nov 2025   Prob (F-statistic):               0.00
Time:                        20:42:35   Log-Likelihood:                 8458.8
No. Observations:              106641   AIC:                        -1.617e+04
Df Residuals:                  106269   BIC:                        -1.261e+04
Df Model:                         371
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0743      0.075     -0.996      0.319      -0.221       0.072
x1            -0.1386      0.076     -1.832      0.067      -0.287       0.010
x2            -0.0793      0.083     -0.955      0.340      -0.242       0.083
x3             0.1136      0.078      1.454      0.146      -0.039       0.267
x4             0.0629      0.075      0.839      0.401      -0.084       0.210
x5             0.0772      0.097      0.795      0.426      -0.113       0.268
x6             0.2287      0.080      2.858      0.004       0.072       0.386
x7             0.3696      0.076      4.839      0.000       0.220       0.519
x8             0.1650      0.080      2.061      0.039       0.008       0.322
x9             0.1334      0.076      1.752      0.080      -0.016       0.283
x10            0.0932      0.091      1.028      0.304      -0.084       0.271
x11            0.0613      0.106      0.581      0.561      -0.146       0.268
x12            0.0644      0.092      0.698      0.485      -0.117       0.245
x13            0.4655      0.078      5.986      0.000       0.313       0.618
x14            0.0796      0.075      1.062      0.288      -0.067       0.227
x15           -0.0047      0.091     -0.052      0.958      -0.182       0.173
x16            0.1070      0.079      1.347      0.178      -0.049       0.263
x17            0.1804      0.083      2.162      0.031       0.017       0.344
x18            0.0140      0.109      0.128      0.898      -0.199       0.227
x19            0.4112      0.090      4.575      0.000       0.235       0.587
x20            0.0453      0.149      0.303      0.762      -0.247       0.338
x21            0.0864      0.109      0.794      0.427      -0.127       0.300
x22            0.3011      0.075      4.019      0.000       0.154       0.448
x23            0.2282      0.078      2.929      0.003       0.076       0.381
x24            0.2190      0.075      2.920      0.004       0.072       0.366
x25            0.2676      0.076      3.505      0.000       0.118       0.417
x26            0.6962      0.080      8.707      0.000       0.539       0.853
x27            0.3485      0.078      4.476      0.000       0.196       0.501
x28            0.2097      0.236      0.888      0.374      -0.253       0.672
x29            0.1790      0.093      1.919      0.055      -0.004       0.362
x30            0.2196      0.080      2.743      0.006       0.063       0.376
x31            0.2647      0.125      2.119      0.034       0.020       0.509
x32            0.5961      0.078      7.659      0.000       0.444       0.749
x33            0.1375      0.082      1.676      0.094      -0.023       0.298
x34            0.1081      0.078      1.390      0.165      -0.044       0.260
x35            0.2098      0.075      2.794      0.005       0.063       0.357
x36            0.3978      0.094      4.214      0.000       0.213       0.583
x37            0.1432      0.081      1.771      0.077      -0.015       0.302
x38            0.4284      0.075      5.715      0.000       0.281       0.575
x39            0.1738      0.135      1.292      0.196      -0.090       0.438
x40            0.1839      0.076      2.433      0.015       0.036       0.332
x41            0.2787      0.080      3.496      0.000       0.122       0.435
x42            0.3364      0.076      4.420      0.000       0.187       0.485
x43            0.1807      0.113      1.602      0.109      -0.040       0.402
x44            0.6824      0.089      7.650      0.000       0.508       0.857
x45            0.6594      0.077      8.538      0.000       0.508       0.811
x46            0.5026      0.080      6.251      0.000       0.345       0.660
x47            0.3519      0.135      2.615      0.009       0.088       0.616
x48            0.3446      0.092      3.734      0.000       0.164       0.526
x49            0.2672      0.125      2.140      0.032       0.022       0.512
x50            0.2919      0.103      2.837      0.005       0.090       0.494
x51            0.8153      0.079     10.370      0.000       0.661       0.969
x52            0.2836      0.075      3.770      0.000       0.136       0.431
x53            0.2962      0.103      2.879      0.004       0.095       0.498
x54            0.3454      0.081      4.279      0.000       0.187       0.504
x55            0.4698      0.096      4.911      0.000       0.282       0.657
x56            0.3950      0.113      3.501      0.000       0.174       0.616
x57            0.3208      0.081      3.974      0.000       0.163       0.479
x58           -0.0122      0.149     -0.082      0.935      -0.305       0.280
x59           -0.0176      0.075     -0.234      0.815      -0.165       0.130
x60            0.2941      0.096      3.074      0.002       0.107       0.482
x61            0.2140      0.082      2.617      0.009       0.054       0.374
x62            0.1900      0.103      1.847      0.065      -0.012       0.392
x63            0.4301      0.087      4.941      0.000       0.260       0.601
x64            0.4144      0.079      5.274      0.000       0.260       0.568
x65            0.6091      0.075      8.136      0.000       0.462       0.756
x66            0.2385      0.135      1.772      0.076      -0.025       0.502
x67            0.2140      0.082      2.622      0.009       0.054       0.374
x68            0.1469      0.175      0.839      0.401      -0.196       0.490
x69            0.2648      0.118      2.243      0.025       0.033       0.496
x70            0.5675      0.083      6.800      0.000       0.404       0.731
x71            0.2307      0.075      3.070      0.002       0.083       0.378
x72            0.1829      0.076      2.391      0.017       0.033       0.333
x73            0.2298      0.079      2.898      0.004       0.074       0.385
x74            0.3095      0.101      3.076      0.002       0.112       0.507
x75            0.2107      0.135      1.566      0.117      -0.053       0.474
x76            0.0290      0.103      0.282      0.778      -0.173       0.231
x77           -0.0154      0.075     -0.205      0.837      -0.163       0.132
x78           -0.2635      0.149     -1.765      0.078      -0.556       0.029
x79            0.0972      0.236      0.412      0.680      -0.365       0.560
x80           -0.0268      0.085     -0.316      0.752      -0.193       0.139
x81           -0.0080      0.075     -0.106      0.915      -0.155       0.139
x82            0.1148      0.075      1.535      0.125      -0.032       0.261
x83            0.2493      0.077      3.250      0.001       0.099       0.400
x84            0.0735      0.077      0.950      0.342      -0.078       0.225
x85            0.0871      0.149      0.583      0.560      -0.205       0.380
x86            0.0008      0.079      0.009      0.992      -0.155       0.156
x87           -0.0306      0.075     -0.409      0.683      -0.177       0.116
x88           -0.0166      0.081     -0.206      0.837      -0.175       0.142
x89            0.2322      0.080      2.895      0.004       0.075       0.389
x90           -0.0072      0.103     -0.070      0.944      -0.209       0.194
x91           -0.0464      0.082     -0.564      0.573      -0.208       0.115
x92            0.0137      0.077      0.179      0.858      -0.136       0.164
x93            0.1168      0.092      1.265      0.206      -0.064       0.298
x94           -0.0167      0.075     -0.222      0.824      -0.164       0.130
x95            0.0806      0.075      1.078      0.281      -0.066       0.227
x96           -0.1701      0.175     -0.972      0.331      -0.513       0.173
x97           -0.1496      0.082     -1.819      0.069      -0.311       0.012
x98           -0.1163      0.094     -1.232      0.218      -0.301       0.069
x99            0.1792      0.087      2.059      0.040       0.009       0.350
x100           0.0645      0.079      0.819      0.413      -0.090       0.219
x101           0.2028      0.082      2.461      0.014       0.041       0.364
x102           0.3415      0.081      4.219      0.000       0.183       0.500
x103           0.1243      0.087      1.436      0.151      -0.045       0.294
x104           0.1628      0.077      2.125      0.034       0.013       0.313
x105           0.0310      0.113      0.275      0.784      -0.190       0.252
x106           0.0600      0.149      0.402      0.688      -0.233       0.353
x107           0.0301      0.096      0.314      0.753      -0.157       0.218
x108           0.2790      0.079      3.512      0.000       0.123       0.435
x109           0.0784      0.075      1.047      0.295      -0.068       0.225
x110         5.12e-05      0.085      0.001      1.000      -0.167       0.168
x111           0.1482      0.075      1.980      0.048       0.002       0.295
x112           0.0789      0.094      0.836      0.403      -0.106       0.264
x113          -0.0455      0.125     -0.365      0.715      -0.290       0.199
x114           0.0822      0.175      0.470      0.639      -0.261       0.425
x115           0.0768      0.075      1.021      0.307      -0.071       0.224
x116          -0.5807      0.175     -3.318      0.001      -0.924      -0.238
x117          -0.1452      0.087     -1.677      0.094      -0.315       0.025
x118           0.1808      0.075      2.404      0.016       0.033       0.328
x119           0.1177      0.078      1.509      0.131      -0.035       0.271
x120           0.2796      0.075      3.739      0.000       0.133       0.426
x121           0.3966      0.092      4.297      0.000       0.216       0.577
x122           0.2057      0.076      2.694      0.007       0.056       0.355
x123           0.0959      0.149      0.642      0.521      -0.197       0.388
x124           0.1718      0.088      1.952      0.051      -0.001       0.344
x125           0.0103      0.081      0.127      0.899      -0.149       0.170
x126           0.0401      0.085      0.473      0.636      -0.126       0.206
x127           0.2543      0.083      3.064      0.002       0.092       0.417
x128           0.0680      0.080      0.855      0.392      -0.088       0.224
x129           0.0364      0.075      0.485      0.628      -0.111       0.183
x130           0.1850      0.075      2.473      0.013       0.038       0.332
x131           0.0351      0.094      0.372      0.710      -0.150       0.220
x132           0.0458      0.106      0.434      0.664      -0.161       0.253
x133          -0.0098      0.083     -0.118      0.906      -0.172       0.152
x134          -0.1046      0.080     -1.313      0.189      -0.261       0.052
x135          -0.2833      0.149     -1.898      0.058      -0.576       0.009
x136          -0.2391      0.087     -2.747      0.006      -0.410      -0.069
x137           0.0331      0.075      0.443      0.658      -0.114       0.180
x138          -0.0299      0.094     -0.317      0.752      -0.215       0.155
x139          -0.0339      0.075     -0.452      0.651      -0.181       0.113
x140           0.2278      0.077      2.976      0.003       0.078       0.378
x141           0.0885      0.075      1.183      0.237      -0.058       0.235
x142           0.0845      0.149      0.566      0.571      -0.208       0.377
x143          -0.0391      0.075     -0.520      0.603      -0.187       0.108
x144          -0.0716      0.075     -0.958      0.338      -0.218       0.075
x145          -0.0516      0.082     -0.626      0.531      -0.213       0.110
x146           0.2047      0.091      2.240      0.025       0.026       0.384
x147           0.0475      0.082      0.581      0.561      -0.113       0.208
x148          -0.1038      0.075     -1.383      0.167      -0.251       0.043
x149           0.0325      0.077      0.423      0.672      -0.118       0.183
x150           0.1224      0.089      1.372      0.170      -0.052       0.297
x151          -0.0214      0.091     -0.234      0.815      -0.201       0.158
x152          -0.1481      0.079     -1.885      0.059      -0.302       0.006
x153          -0.1787      0.090     -1.989      0.047      -0.355      -0.003
x154          -0.3620      0.085     -4.237      0.000      -0.529      -0.195
x155          -0.4581      0.078     -5.891      0.000      -0.611      -0.306
x156          -0.0186      0.077     -0.243      0.808      -0.169       0.131
x157          -0.0630      0.087     -0.724      0.469      -0.234       0.108
x158          -0.2619      0.096     -2.738      0.006      -0.449      -0.074
x159           0.0175      0.075      0.232      0.817      -0.130       0.165
x160           0.1520      0.075      2.023      0.043       0.005       0.299
x161          -0.0069      0.149     -0.046      0.963      -0.299       0.286
x162          -0.1732      0.075     -2.312      0.021      -0.320      -0.026
x163          -0.2144      0.075     -2.868      0.004      -0.361      -0.068
x164          -0.2306      0.075     -3.072      0.002      -0.378      -0.083
x165           0.0123      0.080      0.153      0.879      -0.145       0.169
x166          -0.1032      0.084     -1.234      0.217      -0.267       0.061
x167          -0.1948      0.081     -2.391      0.017      -0.354      -0.035
x168          -0.2055      0.082     -2.498      0.012      -0.367      -0.044
x169          -0.0275      0.075     -0.367      0.714      -0.175       0.120
x170          -0.1775      0.081     -2.182      0.029      -0.337      -0.018
x171          -0.0808      0.078     -1.033      0.302      -0.234       0.073
x172          -0.0437      0.082     -0.535      0.593      -0.204       0.116
x173          -0.5293      0.077     -6.858      0.000      -0.681      -0.378
x174          -0.2608      0.075     -3.461      0.001      -0.408      -0.113
x175           0.0453      0.078      0.581      0.561      -0.107       0.198
x176          -0.0488      0.082     -0.592      0.554      -0.210       0.113
x177          -0.0192      0.077     -0.250      0.802      -0.170       0.131
x178           0.0453      0.075      0.606      0.544      -0.101       0.192
x179           0.1825      0.076      2.397      0.017       0.033       0.332
x180           0.0843      0.118      0.715      0.475      -0.147       0.316
x181          -0.0407      0.075     -0.543      0.587      -0.188       0.106
x182          -0.1349      0.085     -1.579      0.114      -0.302       0.033
x183          -0.0727      0.094     -0.771      0.441      -0.258       0.112
x184           0.1903      0.089      2.148      0.032       0.017       0.364
x185          -0.0304      0.077     -0.398      0.691      -0.180       0.120
x186          -0.0997      0.075     -1.329      0.184      -0.247       0.047
x187           0.0056      0.077      0.073      0.942      -0.145       0.156
x188           0.0926      0.090      1.030      0.303      -0.084       0.269
x189          -0.1433      0.149     -0.960      0.337      -0.436       0.149
x190           0.0908      0.075      1.212      0.225      -0.056       0.238
x191          -0.3288      0.236     -1.393      0.164      -0.791       0.134
x192           0.0600      0.175      0.343      0.732      -0.283       0.403
x193          -0.1140      0.149     -0.764      0.445      -0.407       0.179
x194           0.2048      0.125      1.640      0.101      -0.040       0.450
x195           0.1352      0.075      1.800      0.072      -0.012       0.283
x196           0.0936      0.106      0.887      0.375      -0.113       0.300
x197           0.2015      0.084      2.386      0.017       0.036       0.367
x198           0.2138      0.084      2.555      0.011       0.050       0.378
x199           0.1048      0.149      0.702      0.483      -0.188       0.397
x200           0.0829      0.149      0.555      0.579      -0.210       0.375
x201           0.0191      0.106      0.181      0.856      -0.188       0.226
x202           0.2617      0.082      3.189      0.001       0.101       0.423
x203           0.0651      0.101      0.646      0.518      -0.132       0.262
x204           0.0009      0.125      0.008      0.994      -0.244       0.246
x205           0.1224      0.085      1.439      0.150      -0.044       0.289
x206           0.1203      0.103      1.169      0.242      -0.081       0.322
x207           0.1895      0.149      1.269      0.204      -0.103       0.482
x208           0.0669      0.097      0.689      0.491      -0.123       0.257
x209           0.0322      0.084      0.384      0.701      -0.132       0.197
x210          -0.2758      0.085     -3.228      0.001      -0.443      -0.108
x211          -0.1042      0.077     -1.353      0.176      -0.255       0.047
x212           0.2045      0.079      2.602      0.009       0.050       0.359
x213           0.0782      0.125      0.626      0.531      -0.167       0.323
x214           0.0576      0.087      0.666      0.506      -0.112       0.227
x215           0.2540      0.075      3.390      0.001       0.107       0.401
x216           0.3334      0.075      4.454      0.000       0.187       0.480
x217           0.3472      0.075      4.647      0.000       0.201       0.494
x218           0.1117      0.236      0.473      0.636      -0.351       0.574
x219           0.0440      0.075      0.583      0.560      -0.104       0.192
x220           0.0816      0.089      0.921      0.357      -0.092       0.255
x221           0.2339      0.118      1.982      0.047       0.003       0.465
x222           0.0597      0.089      0.669      0.504      -0.115       0.234
x223           0.0261      0.080      0.327      0.744      -0.130       0.182
x224           0.2099      0.135      1.560      0.119      -0.054       0.474
x225           0.1886      0.096      1.971      0.049       0.001       0.376
x226           0.0263      0.175      0.150      0.881      -0.317       0.369
x227           0.0972      0.125      0.778      0.436      -0.148       0.342
x228           0.0616      0.084      0.734      0.463      -0.103       0.226
x229          -0.0731      0.149     -0.490      0.624      -0.366       0.219
x230           0.3076      0.075      4.110      0.000       0.161       0.454
x231           0.1987      0.103      1.931      0.053      -0.003       0.400
x232           0.1792      0.093      1.921      0.055      -0.004       0.362
x233           0.3989      0.075      5.333      0.000       0.252       0.545
x234           0.4562      0.075      6.085      0.000       0.309       0.603
x235           0.3030      0.080      3.782      0.000       0.146       0.460
x236           0.1952      0.076      2.581      0.010       0.047       0.343
x237           0.1669      0.075      2.217      0.027       0.019       0.315
x238           0.2708      0.106      2.566      0.010       0.064       0.478