In [2]:
import pandas as pd

In [ ]:
from pathlib import Path

dir_path = Path('/home/adambiel/pep-compass/results/lebo/Hydrophobicity')
csv_files = sorted(dir_path.glob('*.csv'))

data = []

# time,sequence,score,latent_point

for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    
    if len(df) < 1400:
        continue
    
    starting_peptide = str(csv_file).split('/')[-1].split('_')[0]
    
    data.append({
        "starting_peptide": starting_peptide,
        "the_best_peptide": df.loc[df['score'].idxmax()]['sequence'],
        "the_best_score": df['score'].max(),
        "scores": df['score'].tolist(),
        "peptides": df['sequence'].tolist()
    })
    
summary_df = pd.DataFrame(data)
summary_df[["starting_peptide", "the_best_peptide", "the_best_score"]]

       starting_peptide           the_best_peptide  the_best_score
0        FLYKWWIRIGRLKL    VIIWWWIIIIIIIIIIIIIIIII        1.310000
1        FLYKWWIRIGRLKL  FIVIWWIIIIVIIIIIIIIIIIIIF        1.312800
2        FLYKWWIRIGRLKL  FLIWWWIFLAIIIVWIVIIIIIIII        1.210400
3        FLYKWWIRIGRLKL  FIIWWWVFIVIIWIIIIIIIIIIII        1.265600
4        FLYKWWIRIGRLKL  IIIFWWIWIVWIIIIIIIIIIIIII        1.285600
5        FLYKWWIRIGRLKL  FIVWWWIWIVIIIIIIIIIIIIIII        1.273600
6        FLYKWWIRIGRLKL  FLFWWWFFIVIIVIIIIIIIIIIII        1.261200
7        FLYKWWIRIGRLKL  ILIWWWFFVIVIWIIIVIIIIIIII        1.241600
8        FLYKWWIRIGRLKL   IIIWWWIWIIFIWFIIVIIIIIII        1.247917
9        FLYKWWIRIGRLKL  IIIWWWIWIIIIWWIIIIIIIIIFI        1.250400
10     KFRNRHRWKFKLIFRN  LVFIWIIWIIIIIIIIIIIIIIIII        1.320800
11     KFRNRHRWKFKLIFRN  WIWFWWIWWIWIFIIFVIIIIIIII        1.198800
12     KFRNRHRWKFKLIFRN  LIRIWIIWIIWIIIIIIIIIIIIII        1.161200
13     KFRNRHRWKFKLIFRN  WIWFWIIWIIIIIIIIIIIIIIIII        1.297600
14     KFRNRHRWKFKLIFRN   WIVFWIIWWIWLIIIVIIIIIIII        1.231250
15     KKYWLIRKWIRLWFLT  LWIWIIIIWLIIWIIIIIIFIIIII        1.273600
16     KKYWLIRKWIRLWFLT   LWIWLILWWIIIIFIIIIIIIIII        1.255833
17     KKYWLIRKWIRLWFLT  LWVWLIIIWLIIIIIVVIIIIIIFI        1.249200
18     KKYWLIRKWIRLWFLT  LWVWIIIIWIIIIIIIIIIIIIIII        1.305200
19     KKYWLIRKWIRLWFLT   LWIWIILWWIILWIIIIIIIIIII        1.239583
20           KTLKIIRLLF         WIIWIIIIIIIIIIIIII        1.334444
21           KTLKIIRLLF   WILWIIIIIIIIIIIIIIIIFIII        1.330000
22           KTLKIIRLLF    WLIWIIWIIIIIIIIVIIIIIII        1.296957
23           KTLKIIRLLF          WIIFIIIIIIIIIIIII        1.353529
24           KTLKIIRLLF  WIIWILWIIIIIIFIIIIIIIIIII        1.309200
25           KTLKIIRLLF    WIIWIIWIIIFIIIIIIIIIIII        1.314348
26           KTLKIIRLLF  WIIWIIWIFIIIIVFIIIIIIFIII        1.293200
27       KYCRRFRWLTFRWL    WIIIWIIWIIIIIIIIIIIIIII        1.323043
28       KYCRRFRWLTFRWL  WIVWWIWWIIIIIIIIIIIIIIIII        1.270000
29       KYCRRFRWLTFRWL  LFFWWWWWLIIWWIIIIIIIIIIII        1.194800
30       KYCRRFRWLTFRWL  WFFVWIIWIIIIWIFIIIIIIIIII        1.269600
31       KYCRRFRWLTFRWL  LWIWWIIWIIIIIIIIIIIIIIIII        1.293600
32  RMARNLVRYVQGLKKKKVI  RVVILIIWIVWFILWWIIIIIIIII        1.081600
33  RMARNLVRYVQGLKKKKVI  RAAFNIVWFLWVILWWIIIIIIIFI        0.928000
34  RMARNLVRYVQGLKKKKVI  RLMFWIVWFLLVIWWWIWWIIFFFF        0.940400
35  RMARNLVRYVQGLKKKKVI  RIVRILFFIMWVMLWWWIFWIIFFI        0.821200
36  RMARNLVRYVQGLKKKKVI  RIVWILVWIVWIMWFWWWIIIIIII        0.992400
37  RMARNLVRYVQGLKKKKVI  RFMWLLIWWVIVVIWWWIIIIIFII        0.996000
38  RMARNLVRYVQGLKKKKVI  RVVWLIIWILWIVWWWWWWWIFFIF        0.924000
39  RMARNLVRYVQGLKKKKVI  RIMFIIVIIVIIIWWWWIIIIIFII        1.079200

In [ ]:
from pathlib import Path

dir_path = Path('/home/adambiel/pep-compass/results/lebo_K_MUTANG_1e-06_K_SORBES_inf/ToxiPep')
csv_files = sorted(dir_path.glob('*.csv'))

data = []

# time,sequence,score,latent_point

for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    
    if len(df) < 1400:
        continue
    
    starting_peptide = str(csv_file).split('/')[-1].split('_')[0]
    
    data.append({
        "starting_peptide": starting_peptide,
        "the_best_peptide": df.loc[df['score'].idxmin()]['sequence'],
        "the_best_score": df['score'].min(),
        "scores": df['score'].tolist(),
        "peptides": df['sequence'].tolist()
    })
    
summary_df = pd.DataFrame(data)
summary_df[["starting_peptide", "the_best_peptide", "the_best_score"]]

       starting_peptide           the_best_peptide  the_best_score
0            KTLKIIRLLF  KEDWFFLFLLFDVYRFYFRRFRRVV        0.015958
1            KTLKIIRLLF  KHDRYWRAFYRLYRYYYFRRFRRVL        0.014634
2   RMARNLVRYVQGLKKKKVI  REAWDLLWFLWYVRYWWWRRRRRRR        0.015912
3   RMARNLVRYVQGLKKKKVI  RMVFLWFYRYLDMVWYFFRRYRRRV        0.014503
4   RMARNLVRYVQGLKKKKVI  REAYEFFWYLLFAWYYRRRRYRRRL        0.014830
5   RMARNLVRYVQGLKKKKVI  RMARDLVRFVFVMWWWYRRRYRRLV        0.016714
6   RMARNLVRYVQGLKKKKVI  REMRNLVRYVPGAWWRWRYRFRRTI        0.019768
7   RMARNLVRYVQGLKKKKVI  RIIYNDFWWELFMYWWWRRRRRRLL        0.014734
8   RMARNLVRYVQGLKKKKVI  REARLLVWFVFFDWWWWWWWKRRRR        0.015501
9   RMARNLVRYVQGLKKKKVI  RMARNLVRFVIGDWWWKWRRIRRRI        0.019456
10  RMARNLVRYVQGLKKKKVI  RHMRLLVRYALFEWWWWRWRKRRRL        0.017051
11  RMARNLVRYVQGLKKKKVI  RMAYNLVRFVFVDWYRFRRRFRRVV        0.017803

In [8]:
summary_df.groupby('starting_peptide')["the_best_score"].mean()

starting_peptide
KTLKIIRLLF             0.015296
RMARNLVRYVQGLKKKKVI    0.016627
Name: the_best_score, dtype: float64